### ISSUE TITLE
FR: Please have a button to copy lat and long so I can copy and paste it in osmand and/or organic maps

### ISSUE THREAD

**Issue by Raj2032** [Divested-Mobile/Maps#3]
In order to use osmand and organic maps more, I wish that GMaps WV would have a button which allows you to copy the lat and long, that way it can be pasted into osmand and/or organic maps.

**Comment by Bugaddr** [comment]
At the same time we can also add option 'open in other app' maybe

**Comment by Raj2032** [comment]
If organic maps and osm maps supports it and it copies and pastes the lats and longs since a lot of the addresses aren't available for OpenStreetMaps.
------- Original Message -------
